server:
  port: 10500
spring:
  application:
    name: summary-seckill
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.100.203:33306/${spring.application.name}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zfxmz
  data:
    redis:
      host: 192.168.100.205
      port: 6379
      password: 123456
      database: 12
      timeout: 5000

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.100.207:18848?username=nacos&password=nacos

rocketmq:
  name-server: 192.168.100.205:9876
  producer:
    group: summary

logging:
  config: classpath:logback.xml
  level:
    com.summary: debug

mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/*.xml
    - classpath*:/repository/*.xml