services:
  elasticsearch:
    image: elasticsearch:8.5.3
    container_name: elasticsearch
    restart: always
    environment:
      ES_JAVA_OPTS: -Xms1024m -Xmx1024m
      discovery.type: single-node
    volumes:
      - /mnt/support/data/elasticsearch/config:/usr/share/elasticsearch/config
      - /mnt/support/data/elasticsearch/data:/usr/share/elasticsearch/data
      - /mnt/support/data/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      elastic-network:
  logstash:
    image: logstash:8.5.3
    container_name: logstash8.5.3
    restart: always
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - /mnt/support/data/logstash/config:/usr/share/logstash/config
      - /mnt/support/data/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
      - "5002:5002"
      - "5004:5004"
      - "5006:5006"
    depends_on:
      - elasticsearch
    networks:
      elastic-network:
  kibana:
    image: kibana:8.5.3
    container_name: kibana8.5.3
    restart: always
    ports:
      - 5601:5601
    volumes:
      - /mnt/support/data/kibana/config:/usr/share/kibana/config
    depends_on:
      - elasticsearch
    networks:
      elastic-network:
networks:
  elastic-network:
    driver: bridge