services:
  elasticsearch:
    image: elasticsearch:7.17.16
    container_name: elasticsearch
    restart: always
    environment:
      ES_JAVA_OPTS: -Xms1024m -Xmx1024m
      discovery.type: single-node
      ELASTIC_PASSWORD: 123456
    volumes:
      - /mnt/support/data/elasticsearch7/config:/usr/share/elasticsearch/config
      - /mnt/support/data/elasticsearch7/data:/usr/share/elasticsearch/data
      - /mnt/support/data/elasticsearch7/plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      elastic-network:
  logstash:
    image: logstash:7.17.16
    container_name: logstash
    restart: always
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - /mnt/support/data/logstash7/config:/usr/share/logstash/config
      - /mnt/support/data/logstash7/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
      - "5002:5002"
      - "5004:5004"
      - "5006:5006"
    depends_on:
      - elasticsearch
    networks:
      elastic-network:
  kibana:
    image: kibana:7.17.16
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    volumes:
      - /mnt/support/data/kibana7/config:/usr/share/kibana/config
    depends_on:
      - elasticsearch
    networks:
      elastic-network:
networks:
  elastic-network:
    driver: bridge