server:
  port: 5000
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: summary-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.207:18848
        username: nacos
        password: nacos
    sentinel:
      enabled: true
      transport:
        dashboard: 192.168.31.7:8844
        port: 8719
    openfeign:
      client:
        config:
          default:
            # 指定Feign客户端连接提供者的超时时限，取决于网络
            connectTimeout: 60000
            # 指定Feign客户端从请求到获取到提供者给出的响应的超时时限  取决于业务逻辑执行时间
            readTimeout: 60000
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      # 开启跨域访问功能
      globalcors:
        cors-configurations:
          # 匹配所有请求
          '[/**]':
            # 跨域处理 允许所有的域
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: front-manager
          uri: lb://summary-front-manager
          predicates:
            - Path=/api/manager/**
          filters:
            - StripPrefix=1
        - id: front-web
          uri: lb://summary-front-web
          predicates:
            - Path=/api/web/**
          filters:
            - StripPrefix=1
            # #请求数限流
            - name: RequestRateLimiter
              args:
                # 用于限流的键的解析器的 Bean 对象的名字
                # SpEL 表达式根据#{@beanName} 从Spring 容器中获取 Bean 对象
                key-resolver: "#{@ipKeyResolver}"
                # 令牌桶每秒填充平均速率  允许每秒处理了多少个请求
                redis-rate-limiter.replenishRate: 100
                # 令牌桶总容量
                redis-rate-limiter.burstCapacity: 300
  data:
    redis:
      host: 192.168.100.205
      port: 6379
      password: 123456
      database: 12
      timeout: 5000

logging:
  config: classpath:logback.xml
  level:
    com.summary: debug
