FROM elasticsearch:7.7.0
MAINTAINER elasticsearch-zh from date UTC by Asia/Shanghai "luoj@ajzxjk.com"
ENV TZ Asia/Shanghai
COPY elasticsearch.yml /usr/share/elasticsearch/config/


# 制作镜像
# docker build -t summary/elasticsearch:7.7.0 .

