spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: summary-goods
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.100.203:33306/${spring.application.name}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zfxmz
  data:
    redis:
      host: 192.168.31.100
      port: 6379
      password: 123456
      database: 12
      timeout: 5000

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.31.100:8848?username=nacos&password=nacos
  consumer:
    timeout: 60000
    check: false
  provider:
    timeout: 60000

rocketmq:
  name-server: 192.168.31.100:9876
  producer:
    group: summary

logging:
  config: classpath:log4j2.xml
  level:
    com.summary: debug

mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/*.xml
    - classpath*:/repository/*.xml

summary:
  log:
    web-flag: false