server:
  port: 20100
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: summary-front-manager
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.100:8848
        username: nacos
        password: nacos
  data:
    redis:
      host: 192.168.31.100
      port: 6379
      password: 123456
      database: 12
      timeout: 5000

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.31.100:8848?username=nacos&password=nacos
  consumer:
    timeout: 60000
    check: false
  provider:
    timeout: 60000

rocketmq:
  name-server: 192.168.31.100:9876
  producer:
    group: summary

logging:
  config: classpath:logback.xml
  level:
    com.summary: debug
    com.alibaba: debug

# 不鉴权的链接
summary:
  auth:
    anon:
      path:
        - /admin/login/username