server:
  port: 10400
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: summary-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.100.203:33306/${spring.application.name}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zfxmz
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.207:18848
        username: nacos
        password: nacos

logging:
  config: classpath:logback.xml
  level:
    com.summary: debug
    com.alibaba: debug

mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/*.xml
    - classpath*:/repository/*.xml