server:
  port: 10600
spring:
  application:
    name: summary-search
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.31.100:13306/${spring.application.name}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.100:8848
        username: nacos
        password: nacos
  data:
    redis:
      host: 192.168.31.101
      port: 6379
      password: 123456
      database: 12
      timeout: 5000

elasticsearch:
  username: elastic
  password: m3I9YBQmmUGB2DTdsnOm
  hosts:
    - http://192.168.31.101:9200


rocketmq:
  name-server: 192.168.31.100:9876
  producer:
    group: summary

logging:
  config: classpath:log4j2.xml
  level:
    com.summary: debug
    co.elastic: debug

mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/*.xml
    - classpath*:/repository/*.xml

